# Generated by Django 5.0.3 on 2024-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/photo_2024-01-17_01-35-37.jpg', upload_to='user_photos/'),
        ),
    ]
