# Generated by Django 5.0.3 on 2024-04-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksowner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ega', to='books.owner'),
        ),
    ]
